### ISSUE TITLE
 Bad performance while idle

### ISSUE THREAD

**Issue by bdcomp** [sblask/firefox-simple-form-fill#2]
Using the just released about:performance I discovered that Simple Form Fill is slowing down my Firefox while idle:
"Simple Form Fill seems to have slown down Firefox very often. When this happens, the slowdown is generally noticeable"
Impact on framerate: 0 high-impacts, 103 medium-impact.
CPU usage: 1% (total 1415141ms).
System usage: 1% (total 87337ms).
Blocking process calls: 0% (total 0ms).
Measure start: 2299 seconds ago.

Simple Form Fill 1.0.4
Firefox 47
Kubuntu 16.04 64bit

**Comment by sblask** [comment]
My Firefox didn't update yet and my nightly is broken again (I am on Xubuntu 15.10), so I can't check `about:performance`, but I am certain that I cannot do anything about the performance. You can check the code, it doesn't do much. It's most likely a Firefox problem. It seems to have performance issues when something modifies the context menu. I did some testing a while ago with very frequent changes to it and Firefox became unbearably slow...

**Comment by sblask** [comment]
Still can't reproduce. I've got "issues" with other add-ons, but not simple form fill. But even for those I assume it's Firefox' fault.

**Comment by bdcomp** [comment]
@sblask I just reproduced it again - you should right click once in some text input field (not choosing anything or using this add-on).
Later, Impact on framerate, CPU usage and System usage continue to grow, like there is some leak.

After only 1 right click (as described above):
Full name: simpleformfill@sblask.
Impact on framerate: 0 high-impacts, 102 medium-impact.
CPU usage: 4% (total 2184818ms).
System usage: 1% (total 44900ms).
Blocking process calls: 0% (total 0ms).
Measure start: 599 seconds ago.

Please reopen this issue.

**Comment by sblask** [comment]
Ok, now I saw it, but still, there is nothing I can do about it. There is a delay the first time the context menu is constructed, the second time I click on a field, the context menu is there immediately. It's Firefox being slow, there is no other way I can fill the context menu apart from calling the SDK function I call.

I use loads of add-ons, even if all of them would have medium impact, I would still keep them, because their functionality is more important to me than pure performance.
